### ISSUE TITLE
dim independently from buftype

### ISSUE THREAD

**Issue by BimbaLaszlo** [blueyed/vim-diminactive#12]
Why does not dimming the buffers with no `buftype`? I like to see my cursor's window highlighted independetly from the `buftype`. What is the cause of this comparison?

**Comment by blueyed** [comment]
This could become a setting, yes.

However, you are currently given the `g:DimInactiveCallback` setting already, which needs to be a function: https://github.com/blueyed/vim-diminactive/blob/6c76b47534c8a87ce5c24219c38e4fc1321c73f5/plugin/diminactive.vim#L46-60

The idea is to not dim quickfix windows etc.

**Comment by BimbaLaszlo** [comment]
I think a variable containing the blacklist of buftypes or filetypes can solve the problem. (filetypes is for disabling plugin (for example the Unite) buffer)

**Comment by blueyed** [comment]
Agreed.

Do you like to create a pull request for this?

**Comment by BimbaLaszlo** [comment]
Yeah, i can do it. One more quiestion: two variables for blacklist is acceptable (one for `buftype` and another for `filetype`)? Or disabling by `filetype` is enough?

**Comment by blueyed** [comment]
I think two are good, probably using the current defaults.

**Comment by BimbaLaszlo** [comment]
I did the changes.

Sorry for the messup in this issue - i'm new in issue/request things and i don't know how to attach pull request to an exist issue.

**Comment by blueyed** [comment]
It's all fine - solid work! :)

Referencing the issue from the PR is good, and you've done it.

For what's it worth, I've recently learnt that the [hub](https://github.com/github/hub/) tools allows to convert issues into pull requests - but that's usually not done.

Thanks for providing the patch!

**Comment by blueyed** [comment]
Committed in https://github.com/blueyed/vim-diminactive/commit/e480e30fa148a6ad41dbe4fc9980387e53f161d4.

(I has a typo there in the link to the issue (missing `s`))
