### ISSUE TITLE
Feature request: Tmux support.  If I leave the vim pane, dim all the buffers

### ISSUE THREAD

**Issue by sagotsky** [blueyed/vim-diminactive#17]
I'm using vim-tmux-navigator to leave my vim pane.  I don't think that actually matters for implementation but it might provide some hints on detecting when a pane switch occurs.

**Comment by blueyed** [comment]
See https://github.com/blueyed/vim-diminactive/pull/16 and #8.

Does that help?

**Comment by blueyed** [comment]
Apart from that, I am using vim-tmux-navigator myself, and we could use some callback / hook for this.  OTOH using tmux directly seems to be better.

**Comment by sagotsky** [comment]
Maybe?  I'll get back to you on those options.

**Comment by sagotsky** [comment]
Sorry about the delay.
https://github.com/tmux-plugins/vim-tmux-focus-events says it's not working
with neovim yet.  Oh well.

**Comment by blueyed** [comment]
#16 has been merged and works for me - also for Neovim.

See also https://github.com/blueyed/vim-diminactive/pull/23 for skipping this when going to another window.
