### ISSUE TITLE
I'm not sure I understand how to use this.

### ISSUE THREAD

**Issue by mcmire** [blueyed/vim-diminactive#19]
I like the idea of your plugin -- it seems like something that would be super useful. However, I feel like the README does a poor job of selling its usefulness. I'm not sure the video makes things any clearer either -- I'm watching you use different commands and am not able to discern the differences very well.

Let me tell you how I *think* I understand this plugin based on the README:

* There are two different areas of Vim that you can customize for inactive windows: you can disable the syntax highlighting and you can change the color of the colorcolumn.
* You can also apparently do this for buffers too, although I'm not sure how being able to customize the plugin on this level would be useful.
* Also, there's this bit about `FocusGained` and `FocusLost` which I don't really understand. I *am* using tmux and I added the vim-tmux-focus-events plugin, but I'm not sure if I needed to do that or what.
* There are some commands you can use to toggle the areas of Vim that are affected:
  * `DimInactiveOn` and `DimInactiveOff` will let you enable or disable the core functionality of this plugin (that is, the fact that windows are dimmed when inactive). You can also use `DimInactiveToggle` if you want to quickly disable the plugin and then enable it later. (The plugin is enabled by default.)
  * `DimInactiveSyntaxOn` and `DimInactiveSyntaxOff` will let you control whether the plugin changes the syntax highlighting in inactive windows. (I'm not sure what the default is.)
  * `DimInactiveColorcolumnOn` and `DimInactiveColorcolumnOff` will let you control whether the plugin changes the colorcolumn in inactive windows. (I'm not sure what the default is.)
* Lastly, you can disable the plugin from taking effect in certain buffer types and file types. (Is there an example you could provide here?)

If this is correct, would you mind if I submitted a PR to improve the README?

**Comment by mcmire** [comment]
Oh, I forgot -- the other thing is that I'm noticing that by default, inactive windows get a different background, but there's no mention of this in the README, either. Would this fall under syntax? Can you customize this?

**Comment by blueyed** [comment]
> a PR to improve the README

Sure, go for it.

> inactive windows get a different background

It's not really another background, but because of the different setting for `colorcolumn`.

**Comment by blueyed** [comment]
Closing this for the moment.
