### ISSUE TITLE
vundle diminactive

### ISSUE THREAD

**Issue by leodebordo** [blueyed/vim-diminactive#22]
hello blue
i scoll the web since any few month now... but i din't find any topic in : how to install Diminactive with Vundle..
:VundleSearch Diminactive does'n work
Did you have  a idea ?

regards
leodebordo

**Comment by leodebordo** [comment]
issued

**Comment by blueyed** [comment]
For reference, `VundleSearch` appears to use http://vim-scripts.org/vim/scripts.html, which only includes plugins published on vim.org - which I am not doing currently.

@leodebordo 
Not sure if you've found it, but you can install it using the Github's Repo URL probably: https://github.com/blueyed/vim-diminactive

**Comment by leodebordo** [comment]
Many tanX Blueyed that the soluce !

regards

leodebordo
