### ISSUE TITLE
Highlight only 80 columns

### ISSUE THREAD

**Issue by sittim** [blueyed/vim-diminactive#26]
I have a strict code width requirement, it would be awesome to be able to highlight only 80 columns?

**Comment by blueyed** [comment]
Hmm, while that is possible (you can use `let g:diminactive_max_cols = 80` for that), I wonder why you do not want to use only `colorcolumn=80` for the active window?

**Comment by sittim** [comment]
Thank you, let me try `colorcolumn=80`
