### ISSUE TITLE
Change font color of inactive pane?

### ISSUE THREAD

**Issue by purplecones** [blueyed/vim-diminactive#33]
Hello! This is exactly the plugin I am looking for. 

One question I have though is, how do I change the font color for all inactive panes? My current background is black, and I'd like to change the font to dark gray for all inactive panes. Is this possible?

**Comment by blueyed** [comment]
Are you using Neovim?
I will update the plugin soonish to support the new `'winhighlight'` setting (https://github.com/neovim/neovim/pull/6597#issuecomment-300487439), and that allows you to define a highlighting group.  Not sure if it overrides syntax highlighting though, but there is an option already to turn syntax highlighting off for dimming.

**Comment by purplecones** [comment]
I'm using normal vim and with syntax highlighting off it works good. I wasn't able to get it working initially so I was trying to change the font color but it would still be a nice addition.

Will this feature not work in regular vim?

**Comment by blueyed** [comment]
No, `'winhighlight'` is only for Neovim now - I don't know about if it's planned to be submitted as a patch there, or gets picked up from them.
