### ISSUE TITLE
foldmethod reset to global default if g:diminactive_use_syntax = 1

### ISSUE THREAD

**Issue by Jeansen** [blueyed/vim-diminactive#35]
If I have two windows showing two buffers (or I just create a new empty split) and `:set foldmethod=manual` then this will be reset to `foldmethod=syntax` if `g:diminactive_use_syntax = 1`, whenever I change windows.

**Comment by blueyed** [comment]
What filetype is this?
Sounds like (re)setting the syntax triggers this.

**Comment by Jeansen** [comment]
I assume something like this. Filetype is Perl. Looks like this does not happen with other filetypes ....

**Comment by blueyed** [comment]
Do you have set `perl_fold = 1` manually?

**Comment by Jeansen** [comment]
Ah..yes. I am sorry, I did not provide a minimalistic vimrc, yet. On the other hand. I removed `per_fold =1`. Now it works (and vim opens the file A LOT faster) :)

**Comment by blueyed** [comment]
Cool.
Closing this now for then.

Regarding folding speed, see https://github.com/Konfekt/FastFold.

**Comment by blueyed** [comment]
For reference (in case other settings are affected etc(, you could have also used something like the following to override with your setting(s):
```
augroup my_perl
  au!
  autocmd Syntax perl set foldmethod=syntax
augroup END
```

**Comment by Jeansen** [comment]
Thank you very much. Well, for me it works so far. Though on the other hand not setting perl_fold removes the ability to use syntax folding for perl.
