### ISSUE TITLE
use winhl in neovim

### ISSUE THREAD

**Issue by teto** [blueyed/vim-diminactive#38]
hi,
Neovim introduced a window-local option that might be faster to use than say colorcolumn or syntax (quite harmful on my computer), i.e. "winhl".
Also I am a bit sad when there is no doc folder though I could help with that if you agree.

thanks for the cool plugin

**Comment by blueyed** [comment]
Thanks for reminding me.
1. I am using something based on https://github.com/neovim/neovim/pull/6597#issuecomment-299475512 already.

2. docs would be great, maybe just based on the README for now?

**Comment by teto** [comment]
cool. I will send a PR for the doc
