### ISSUE TITLE
fugitive's Gdiff keeps the current version's window dimmed, when ending the diff process (fugitive issue)

### ISSUE THREAD

**Issue by Futile** [blueyed/vim-diminactive#4]
I don't know if this is a problem with fugitive or vim-diminactive, but here is how to reproduce the problem:

   1. Open a file which is under git version control
   2. If the file is currently unsaved, make some changes to it
   3. Run `:Gdiff` (requires fugitive)
   4. Close the split with the indexed version, leaving only the current version
   5. Now this split is inactive, even though it is the only split. `DimInactiveOff` does not make the window active again.

I think step 2 is optional. I actually had to close and reopen vim to get to a non-dimmed version of my file again.

**Comment by blueyed** [comment]
Should be fixed in fugitive now, via https://github.com/tpope/vim-fugitive/commit/e065e4f841f4a033ac9a6156573a446007617b1d.
