### ISSUE TITLE
Feature Request:  Expose an argument to specify what the dimmed color or amount should be.

### ISSUE THREAD

**Issue by jgors** [blueyed/vim-diminactive#9]
It would be really great if there was a way to be able to specify a given color (or level of shading) to be used when the panes are inactive (rather than the default pink color that appears on my vim setup).

**Comment by blueyed** [comment]
It uses the `ColorColumn` highlighting definition.

I agree that there could be some mechanism to fix this with the default theme, or when a theme does not adjust it.

What colorscheme are you using?
What does `:hi ColorColumn` give you?

For the time being, you could try this (or some variant):

    :hi ColorColumn ctermbg=0 guibg=#eee8d5

**Comment by jgors** [comment]
ah, i see...makes sense.  and i'm using my own colorscheme, where I didn't have `ColorColunm` defined.  thanks for the pointer here.
